version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:8.11.1
    steps:
      - run:
          - checkout
          - npm run lint

  test:
    docker:
      - image: circleci/node:8.11.1
    steps:
      - run:
          - checkout
          - npm run test

  analyze:
    docker:
      - image: circleci/node:8.11.1
    steps:
      - run: 
          - checkout
          - npm run audit

workflows:
  build:
    jobs:
      - build
      - test:
          requires:
            - build
      - analyze:
          requires:
            - test
